#! /bin/bash

source ./src/config.sh

CONFIG_DIR="$WORKING_DIR/config"
INSTALLER="./installer"

mkdir -p $CONFIG_DIR

mkdir $CONFIG_DIR/aws
mkdir $CONFIG_DIR/firefox
mkdir $CONFIG_DIR/bin

cp ~/.aws/* $CONFIG_DIR/aws
cp ~/snap/firefox/common/.mozilla/firefox/*.default/user.js $CONFIG_DIR/firefox
cp ~/desk/Pictures/wallpaper.png $CONFIG_DIR/wallpaper.png
cp ~/bin/* $CONFIG_DIR/bin
cp ~/.config/user-dirs.dirs $CONFIG_DIR/user-dirs.dirs
cp ~/.aliases $CONFIG_DIR/aliases.sh
cp ~/.tmux.conf $CONFIG_DIR/tmux.conf
sudo cp /etc/wireguard/wg0.conf $CONFIG_DIR/wireguard.conf
sudo cp /etc/conky/conky.conf $CONFIG_DIR/conky.conf

konsave -s konsave && konsave -e konsave && konsave -r konsave
mv ./konsave.knsv $CONFIG_DIR/konsave.knsv

tar -czvf $WORKING_DIR/config.tar.gz -C $WORKING_DIR config
CONFIG_DATA=$(base64 -w 0 $WORKING_DIR/config.tar.gz)
rm -rf $WORKING_DIR

echo "#! /bin/bash" > $INSTALLER
echo "mkdir -p $WORKING_DIR" >> $INSTALLER
echo "base64 -d > $WORKING_DIR/config.tar.gz <<< $CONFIG_DATA" >> $INSTALLER

cat ./src/config.sh >> $INSTALLER
echo >> $INSTALLER

cat ./src/install.sh >> $INSTALLER
echo >> $INSTALLER

chmod +x $INSTALLER

rm -rf $WORKING_DIR