#! /bin/bash

WD="/tmp/williams-config-script-$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8; echo)"

INSTALLER=$1
if [[ $# -lt 1 ]]; then
    INSTALLER="./install.sh"
fi

mkdir -p $WD/files

while read -r -a line
do
    if [[ ${#line[@]} -gt 1 && ${line[1]} != "CREATE" ]]; then
        src=$(eval echo "${line[0]}")
        dst=$WD/files/${line[1]}
        sudo cp -r $src $dst
    fi
done < ./config/files.txt

cp -r config $WD

echo '#! /bin/bash' > $WD/main.sh
cat ./src/* >> $WD/main.sh
chmod +x $WD/main.sh

sudo ./util/bundle $WD main.sh $INSTALLER

sudo rm -rf $WD
echo "Written installer to '$INSTALLER'"
echo "Done."
