#! /bin/bash

CONFIG_DIR="./config"

read -p "This will purge your current config. Are you sure? " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

rm -rf $CONFIG_DIR
mkdir $CONFIG_DIR

mkdir $CONFIG_DIR/aws
mkdir $CONFIG_DIR/firefox
mkdir $CONFIG_DIR/bin

cp ~/.aws/* $CONFIG_DIR/aws
cp ~/snap/firefox/common/.mozilla/firefox/*.default/user.js $CONFIG_DIR/firefox
cp ~/desk/Pictures/wallpaper.png $CONFIG_DIR/wallpaper.png
cp ~/bin/* $CONFIG_DIR/bin
cp ~/.config/user-dirs.dirs $CONFIG_DIR/user-dirs.dirs
cp ~/.aliases $CONFIG_DIR/aliases.sh
sudo cp /etc/wireguard/wg0.conf $CONFIG_DIR/wireguard.conf
sudo cp /etc/conky/conky.conf $CONFIG_DIR/conky.conf

SAVE_NAME=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo)
konsave -s $SAVE_NAME && konsave -e $SAVE_NAME && konsave -r $SAVE_NAME
mv ./$SAVE_NAME.knsv $CONFIG_DIR/konsave.knsv