#! /bin/bash

CONFIG_DIR="./config"

read -p "This will purge your current config. Are you sure? " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

rm -rf $CONFIG_DIR
mkdir $CONFIG_DIR

mkdir $CONFIG_DIR/aws
mkdir $CONFIG_DIR/firefox
mkdir $CONFIG_DIR/bin

cp ./apt.txt $CONFIG_DIR/apt.txt
cp ./repos.txt $CONFIG_DIR/repos.txt
cp ./snap.txt $CONFIG_DIR/snap.txt

cp ~/.aws/* $CONFIG_DIR/aws
cp ~/snap/firefox/common/.mozilla/firefox/*.default/user.js $CONFIG_DIR/firefox
cp ~/desk/Pictures/wallpaper.png $CONFIG_DIR/wallpaper.png
cp ~/bin/* $CONFIG_DIR/bin
cp ~/.config/user-dirs.dirs $CONFIG_DIR/user-dirs.dirs
cp ~/.aliases $CONFIG_DIR/aliases.sh
cp ~/.tmux.conf $CONFIG_DIR/tmux.conf
sudo cp /etc/wireguard/wg0.conf $CONFIG_DIR/wireguard.conf
sudo cp /etc/conky/conky.conf $CONFIG_DIR/conky.conf

konsave -s konsave && konsave -e konsave && konsave -r konsave
mv ./konsave.knsv $CONFIG_DIR/konsave.knsv