#! /bin/bash

if [[ $# -lt 2 ]] ; then
	echo 'Usage: bundle <directory> <init script> (out file)'
	exit 0
fi

BUNDLE=$3
if [[ $# -lt 3 ]]; then
    BUNDLE="./bundle.sh"
fi

echo $BUNDLE

WD=/tmp/bundler-$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8; echo)
echo $WD

mkdir -p $WD

tar -C $1 -czvf $WD/bundle.tgz .
gpg --symmetric --cipher-algo AES256 $WD/bundle.tgz

FILE_DATA=$(base64 -w 0 $WD/bundle.tgz.gpg)

echo '#! /bin/bash' > $BUNDLE
echo 'WD=/tmp/unbundler-$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8; echo)' >> $BUNDLE
echo 'mkdir -p $WD/bundle' >> $BUNDLE
echo -n 'base64 -d > $WD/bundle.tgz.gpg <<<' >> $BUNDLE
echo $FILE_DATA >> $BUNDLE
echo 'gpg --decrypt --quiet $WD/bundle.tgz.gpg > $WD/bundle.tgz' >> $BUNDLE
echo 'tar xf $WD/bundle.tgz -C $WD/bundle' >> $BUNDLE
echo 'cd $WD/bundle' >> $BUNDLE
echo -n 'sh $WD/bundle/' >> $BUNDLE
echo "$2" >> $BUNDLE
echo 'rm -rf $WD' >> $BUNDLE

chmod +x $BUNDLE
